#  Mathematical Operations in TensorFlow

### Element-wise Operations
Mathematical operations such as addition, subtraction, and multiplication are performed **element-wise**.  
This means that corresponding elements of the tensors are operated on individually.  
Element-wise operations are the foundation for scaling inputs, combining features, and applying activations.

---

### Broadcasting
When performing operations on tensors of different shapes, TensorFlow applies **broadcasting**.  
Broadcasting extends the smaller tensor along the missing dimensions to match the shape of the larger tensor.  
This allows flexible arithmetic without manual reshaping.

---

### Comparison Operations
TensorFlow supports **element-wise comparison** between tensors.  
The result is a tensor of boolean values (`True` or `False`) depending on whether the corresponding elements are equal.  
This is useful for filtering, masking, and conditional logic.

---

### Power Method
The **power operation** computes the value of one tensor raised to the power of another, performed element-wise.  
This is often used in normalization, polynomial transformations, and scaling.

---

### Matrix Multiplication
Matrix multiplication is central to deep learning.  
It involves multiplying rows of one matrix with columns of another and summing the products.  
Often, one of the matrices may be transposed to align dimensions.  
This operation underpins linear transformations in neural layers.

---

### Scalar Output
Some operations reduce tensors to a **scalar output**.  
For example, summation across all elements collapses dimensions into a single value.  
This reduction is critical for computing loss functions and aggregating results.

---

##  Key Insight
Mathematical operations in TensorFlow are not just computational tools, they are the **language of deep learning**.  

Every forward pass, loss calculation, and weight update is expressed through these operations, making them the theoretical backbone of how models learn and generalize.

In [2]:
import tensorflow as tf

In [3]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

In [4]:
print("Addition:", tf.add(a, b))

Addition: tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [7]:
tf.subtract(a, b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -3, -3], dtype=int32)>

In [9]:
tf.multiply(a, b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4, 10, 18], dtype=int32)>

### Broadcasting

In [10]:
x = tf.constant([[1, 2, 3],
                 [4, 5, 6]])
y = tf.constant([1, 2, 3])  # smaller tensor

In [11]:
tf.add(x, y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 4, 6],
       [5, 7, 9]], dtype=int32)>

## Comparison Operations

In [12]:
a = tf.constant([1, 2, 3])
b = tf.constant([2, 2, 4])

In [14]:
print("Equal:", tf.equal(a, b))   
print("Greater:", tf.greater(a, b)) 

Equal: tf.Tensor([False  True False], shape=(3,), dtype=bool)
Greater: tf.Tensor([False False False], shape=(3,), dtype=bool)


In [15]:
tf.less(a,b)

<tf.Tensor: shape=(3,), dtype=bool, numpy=array([ True, False,  True])>

## Power Method

In [16]:
base = tf.constant([2, 3, 4])
exp = tf.constant([3, 2, 1])

In [17]:
print("Power:", tf.pow(base, exp))

Power: tf.Tensor([8 9 4], shape=(3,), dtype=int32)


## Matrix Multiplication

In [18]:
A = tf.constant([[1, 2],
                 [3, 4]])
B = tf.constant([[5, 6],
                 [7, 8]])

In [20]:
print("Matrix Multiplication:\n", tf.matmul(A, B))

Matrix Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


## Scalar Output

In [21]:
t = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

In [22]:
print("Sum of all elements:", tf.reduce_sum(t))   

Sum of all elements: tf.Tensor(21, shape=(), dtype=int32)


In [23]:
print("Mean of all elements:", tf.reduce_mean(t)) 

Mean of all elements: tf.Tensor(3, shape=(), dtype=int32)


### Variables in Python: Code Examples

##  Variable Definition

In [24]:
# Variable definition with automatic type assignment
x = 10        # integer
y = 3.14      # float
name = "Rock"

In [25]:
print(type(x))    
print(type(y))    
print(type(name)) 

<class 'int'>
<class 'float'>
<class 'str'>


## Variable Scope

In [31]:
# Global variable
global_var = "I am global"

def my_function():
    local_var = "I am local"
    print("Inside function:", local_var)
    print("Inside function accessing global:", global_var)

In [32]:
my_function()

Inside function: I am local
Inside function accessing global: I am global


### Variable Operations

In [34]:
a = 5
b = 10
c = a + b
print("Sum:", c)

Sum: 15
