# TensorFlow in Deep Learning and LLMs

## What is TensorFlow?
TensorFlow is an **open-source deep learning framework** developed by Google.  
It provides a flexible ecosystem for building and training machine learning models, especially those involving **large-scale numerical computations**.

- Designed for **high-performance numerical operations** on tensors  
- Supports both **research prototyping** and **production deployment**  
- Widely used in **computer vision, NLP, and reinforcement learning**

---

## How TensorFlow Works in Deep Learning
Deep learning models rely on **layers of mathematical operations** applied to tensors. TensorFlow acts as the computational engine:

1. **Graph-based computation**  
   - Operations are represented as nodes in a computational graph  
   - Efficient execution across CPUs, GPUs, and TPUs  

2. **Automatic differentiation**  
   - TensorFlow computes gradients automatically  
   - Enables backpropagation for training neural networks  

3. **Scalability**  
   - Handles small experiments and large distributed training seamlessly  

---

## Connection to LLMs (Large Language Models)
LLMs like **BERT, GPT, and T5** are built on deep learning foundations. TensorFlow plays a key role in their development:

- Provides **tensor operations** for handling massive text embeddings  
- Supports **transformer architectures** (self-attention, multi-head attention)  
- Enables **training at scale** with billions of parameters  
- Integrates with libraries like **TensorFlow Hub** and **TensorFlow Serving** for fine-tuning and deployment  

---

## Understanding Tensors
A **tensor** is the fundamental data structure in TensorFlow — a generalization of scalars, vectors, and matrices.

- **Scalar (0D tensor):** Single number → `5`  
- **Vector (1D tensor):** List of numbers → `[1, 2, 3]`  
- **Matrix (2D tensor):** Table of numbers →  `[[1, 2],[3, 4]]`


- **Tensor (nD):** Multi-dimensional array → e.g., `shape = (2, 3, 4)`

---

## Dimensions in Tensors
- **Rank:** Number of dimensions (e.g., scalar = rank 0, vector = rank 1)  
- **Shape:** Size of each dimension (e.g., `(batch_size, sequence_length, embedding_dim)`)  
- **Axis:** Specific dimension index used for operations  

In NLP, tensors represent:
- Word embeddings  
- Sentence embeddings  
- Attention matrices  
- Model parameters  

---

### Key Takeaway
TensorFlow provides the **mathematical backbone** for deep learning.  
By operating on tensors and scaling computations, it enables the training of **LLMs** that power modern NLP applications.



Link : https://www.python.org/ftp/python/3.11.4/python-3.11.4-amd64.exe

In [4]:
pip install tensorflow

                                              0.0/350.8 MB ? eta -:--:--
                                            0.0/350.8 MB 660.6 kB/s eta 0:08:52
                                            0.1/350.8 MB 825.8 kB/s eta 0:07:05
                                              0.1/350.8 MB 1.1 MB/s eta 0:05:34
                                              0.2/350.8 MB 1.5 MB/s eta 0:03:50
                                              0.3/350.8 MB 1.4 MB/s eta 0:04:07
                                              0.4/350.8 MB 1.8 MB/s eta 0:03:13
                                              0.5/350.8 MB 1.9 MB/s eta 0:03:02
                                              0.6/350.8 MB 2.2 MB/s eta 0:02:43
                                              0.7/350.8 MB 2.2 MB/s eta 0:02:40
                                              0.8/350.8 MB 2.3 MB/s eta 0:02:30
                                              0.9/350.8 MB 2.4 MB/s eta 0:02:27
                                              1

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 23.1.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.


In [5]:
# import tensorflow
import tensorflow as tf

# Tensor Creation in TensorFlow

A **Tensor** is like a box that holds numbers.  
- If it holds just one number → it's a **scalar** (like `5`).  
- If it holds a list of numbers → it's a **vector** (like `[1, 2, 3]`).  
- If it holds a table of numbers → it's a **matrix** (like `[[1, 2], [3, 4]]`).  
- If it holds many tables stacked → it's a **tensor** (higher dimensions).

Think of tensors as the **building blocks** of deep learning, everything in TensorFlow is stored and processed as tensors.

---
## What to Call Tensors by Shape

In TensorFlow, everything is a **tensor**, but we often use special names depending on the number of dimensions (the "rank" of the tensor):

- **Scalar (0‑D tensor)** → A single number  
  Example: `tf.constant(5)` → shape `()`  

- **Vector (1‑D tensor)** → A list of numbers (like an array)  
  Example: `tf.constant([1, 2, 3])` → shape `(3,)`  

- **Matrix (2‑D tensor)** → A table of numbers with rows and columns  
  Example: `tf.constant([[1, 2], [3, 4]])` → shape `(2, 2)`  

- **3‑D Tensor** → A cube of numbers (like stacked matrices)  
  Example: `tf.zeros([2, 3, 4])` → shape `(2, 3, 4)`  

- **n‑D Tensor (n > 3)** → Higher‑dimensional structures (used in deep learning for batches, images, etc.)  
  Example: `tf.random.normal([32, 28, 28, 3])` → shape `(32, 28, 28, 3)`  

---

## Key Takeaway
- **Tensor** = general term for any dimensional array.  
- **Scalar, Vector, Matrix** = special names for 0‑D, 1‑D, and 2‑D tensors.  
- Higher dimensions are still tensors, just described by their shape.



## Ways to Create Tensors

In [5]:
### 1. From Python Lists

# Create tensor from a Python list
tensor1 = tf.constant([1, 2, 3, 4])
print(tensor1)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [7]:
tensor1.shape

TensorShape([4])

## 2. With Specific Values

In [8]:
# All zeros
zeros = tf.zeros([2, 3])   # 2 rows, 3 columns
print(zeros)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [9]:
# All ones
ones = tf.ones([2, 3])
print(ones)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


## 3. With Random Numbers

In [10]:
# Random values between 0 and 1
random_tensor = tf.random.uniform([2, 2])
print(random_tensor)

tf.Tensor(
[[0.8491887  0.81491923]
 [0.73337305 0.18804646]], shape=(2, 2), dtype=float32)


In [11]:
# Random normal distribution
normal_tensor = tf.random.normal([2, 2])
print(normal_tensor)

tf.Tensor(
[[ 0.4850892  -0.08950138]
 [-1.0266426   0.25857064]], shape=(2, 2), dtype=float32)


## 4. With Ranges

In [13]:
# Numbers from 0 to 9
range_tensor = tf.range(10)
print(range_tensor)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [28]:
# Scalar (0-D tensor, single value)
scalar = tf.constant(5)
print("Scalar:", scalar)
print("Shape:", scalar) 

Scalar: tf.Tensor(5, shape=(), dtype=int32)
Shape: tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
# Vector (1-D tensor, list of values)
vector = tf.constant([1, 2, 3])
print("\nVector:", vector)
print("Shape:", vector.shape)   


Vector: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Shape: (3,)


In [30]:
# Step 3: Matrix (2-D tensor, rows and columns)
matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6]])
print("\nMatrix:\n", matrix)
print("Shape:", matrix.shape)


Matrix:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Shape: (2, 3)


#  Tensor Data Types in TensorFlow

Every tensor has a **data type (dtype)**.  
This tells TensorFlow what kind of values are stored inside the tensor.  
Choosing the right dtype is important because it affects **memory usage, speed, and precision**.

---

## Common TensorFlow Data Types

- **tf.int32** → Whole numbers (integers)  
- **tf.float32** → Decimal numbers (floating point, default for most operations)  
- **tf.bool** → True/False values  
- **tf.string** → Text values (like `"hello"`)  
- **tf.complex64** → Complex numbers (like `3 + 2j`)  

---

##  Examples

In [21]:
# Integer tensor
int_tensor = tf.constant([1, 2, 3], dtype=tf.int32)
print(int_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [27]:
int_tensor.dtype

tf.int32

In [22]:
# Float tensor
float_tensor = tf.constant([1.0, 2.0, 3.0], dtype=tf.float32)
print(float_tensor)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [23]:
# Boolean tensor
bool_tensor = tf.constant([True, False, True], dtype=tf.bool)
print(bool_tensor)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [24]:
# String tensor
string_tensor = tf.constant(["apple", "banana", "cherry"], dtype=tf.string)
print(string_tensor)

tf.Tensor([b'apple' b'banana' b'cherry'], shape=(3,), dtype=string)


In [26]:
string_tensor.dtype

tf.string

## Casting Tensors in TensorFlow

Sometimes we need to **convert a tensor from one data type to another**.  
For example, changing floats to integers, or integers to booleans.  
TensorFlow provides the **`tf.cast()`** method for this.

---

In [32]:
# Float tensor
float_tensor = tf.constant([1.7, 2.3, -3.9], dtype=tf.float32)

In [34]:
print("Original:", float_tensor)
print("dtype:", float_tensor.dtype)

Original: tf.Tensor([ 1.7  2.3 -3.9], shape=(3,), dtype=float32)
dtype: <dtype: 'float32'>


In [35]:
# Cast float → integer
int_tensor = tf.cast(float_tensor, dtype=tf.int32)

In [36]:
print("Cast to int:", int_tensor)
print("dtype:", int_tensor.dtype)

Cast to int: tf.Tensor([ 1  2 -3], shape=(3,), dtype=int32)
dtype: <dtype: 'int32'>


In [44]:
# Cast integer → boolean
bool_tensor = tf.cast(int_tensor, dtype=tf.bool)

In [45]:
print("Cast to bool:", bool_tensor)
print("dtype:" , bool_tensor.dtype)

Cast to bool: tf.Tensor([ True  True  True], shape=(3,), dtype=bool)
dtype: <dtype: 'bool'>
